name: news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.9
  http: ^1.2.1
  retrofit: ^4.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
